### PR TITLE
Add linkedin

### PR DESCRIPTION
**Pull request by davideapvd**
#12

### CODE REVIEW

**Comment by sarahdib** [comment]
Hello @davideapvd 
Thank you for your pull request.

@TristanLDD I think we need a pictogram for linkedin link what do you think ?
Capture d’écran 2020-01-16 à 22 38 23

**Comment by TristanLDD** [comment]
@sarahdib Yes, here is the Linkedin icon: 

- >  icons8-linkedin-2-96
(it's white on white background)

**Comment by sarahdib** [comment]
@davideapvd could you integrate the icon @TristanLDD provide ?

Thank you

**Comment by davideapvd** [comment]
@sarahdib I think the icons are handled by the base theme https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/css/components/footer.scss#L65 and they all are in svg format (black/white) , am I correct?

**Comment by sarahdib** [comment]
@davideapvd Ok I will upgrade the issue and validate your PR.

**Comment by Progi1984** [comment]
Thanks @davideapvd

**Pull request merged**
