### PR TITLE
Add TikTok

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This PR add a new social network: TikTok.
| Type?         | new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#30229.
| How to test?  | Check if TikTok is present in the module (FO and BO).

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]
LGFM :+1:

**Review by yanmakouf — APPROVED** [review]
👍

**Comment by paulnoelcholot** [comment]
Hello @micka-fdz,

Thanks for your PR. I tested it and it's ok for me. Nevertheless I noticed that it would be necessary to make an addition in the "read more" of the module --> "Features" and change:
"You can add your Facebook, Twitter, YouTube, Google, Instagram, Pinterest, Vimeo pages and even your RSS feed."

By :

"You can add your Facebook, Twitter, YouTube, Google, Instagram, Pinterest, Vimeo, LinkedIn, TikTok and Discord pages and even your RSS feed."

image


Thanks you

**Comment by Hlavtox** [comment]
This description is coming from Addons, they need to update it there. 👍
Ping @kpodemski for merge and merge rights for me 🙏

**Pull request merged**
