### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.3.0
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by Hlavtox** [comment]
@kpodemski Can you please resolve this conflict? 🙏

**Comment by kpodemski** [comment]
@Hlavtox should be good now

**Review by kpodemski — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I have tested this release and I think there is a problem : 
image

**Comment by kpodemski** [comment]
@paulnoelcholot rebase on a fix-conflicts-merge branch

**Pull request merged**
